### ISSUE TITLE
Extra pixel on the left of #poll-select-container

### ISSUE THREAD

**Issue by uriklar** [V2015/election-polls-frontend#6]

**Comment by yuvii** [comment]
@uriklar 
It's kind of a fictional pixel, but it's there alright. I'd go so far as to say it's a webkit issue.

We can probably resolve this by making everything a tad bit wider and disabling x-axis scrolling. What do you think?

**Comment by yuvii** [comment]
[fixed](https://github.com/V2015/election-polls-frontend/commit/4d067268a4dac4cd7d7f3d6b27f5881cab3e3e14)
